= bide
:sectlinks:

image:http://clojars.org/funcool/bide/latest-version.svg["Clojars Project", link="http://clojars.org/funcool/bide"]


== Introduction

A simple routing library for ClojureScript that uses Express like syntax.

[quote, A Basque proverb]
____
Egiak ez ditu bi bide
____


== Install

Add the following dependency to your project.clj file:

[source,clojure]
----
[funcool/bide "0.1.0"]
----


== User Guide

Just import the core namespace and start building the router:

[source, clojure]
----
(ns myapp.core
  (:require [bide.core :as r]))

(def routes
  (r/build [["/api/auth" :myapp/auth]
            ["/api/users/:id" :myapp/user-by-id]]))
----


Now, you can perform a basic operations such that *lookup* and *resolve*:

[source, clojure]
----
(r/lookup routes "/api/auth")
;; => [:myapp/auth {}]

(r/lookup routes "/api/users/1")
;; => [:myapp/user-by-id {:id "1"}]

(r/reverse routes :myapp/auth)
;; => "/api/auth"

(r/reverse routes :myapp/user-by-id {:id 2})
;; => "/api/users/2"
----

And finally, you can integrate it in your ClojureScript web application using
the builtin helpers that uses goog.History api under the hood:

[source, clojure]
----
(defn on-navigate
  "A function which will be called on each route change."
  [name params]
  (println "Route change to: " name params))

(def router
  (r/start! router {:default :myapp/auth
                    :on-navigate on-navigate}))
----

And finally, you can force the navigation trigger using the `navigate!` helper
function:

[source, clojure]
----
(r/navigate! router :myapp/user-by-id {:id 10})
----


== How to Contribute?

Just open an issue or PR ;)


== FAQ

=== Why another routing library?

Just because the existing ones are to complex and with very bloated documentation
that does not explains the essential for the basic use of library.

This library is designed with simplicity in mind and make the url definition much
more eye friendly.

Many other libraries are focusing on using clojure datastructures for represent the
routing in some kind of tree. The concept is very nice but in practice, when you
have complex routing paths, the things becomes dificult to understand. Just let see
an example:

.Real example using *bidi* routing library
[source, clojure]
----
(def routes
  ["/" [["auth/login" :auth/login]
        [["auth/recovery/token/" :token] :auth/recovery]
        ["settings/" [["profile" :settings/profile]
                      ["password" :settings/password]
                      ["notifications" :settings/notifications]]]
        ["workspace/" [[[:project-uuid "/" :page-uuid] :workspace/page]]]]])
---

And then, let see how it can be represented with *bide*:

[source, clojure]
----
(def routes
  [["/auth/login" :auth/login]
   ["/auth/recovery/token/:token" :auth/recovery]
   ["/settings/profile" :settings/profile]
   ["/settings/password" :settings/password]
   ["/settings/notifications" :settings/notifications]
   ["/workspace/:project-uuid/:page-uuid" :workspace/page]])
----

Yes, it has some repetitions in comparison to the bidi example, but in terms of
readability *bide* is a clean winner.

Of course, just now *bide* does not offers all the features that the other libraries,
and many of missing stuff will be added over time. But the main purpose of bide is
to stay *small and simple*.


== License

_bide_ is licensed under BSD (2-Clause) license.
